name       : python-zope.component
version    : 4.5
release    : 4
source     :
    - https://github.com/zopefoundation/zope.component/archive/4.5.tar.gz : a1967e3e2eb9117706e84ed8bb4c4eb5b9ba8929219c89758e233a729a02ac19
license    : ZPL-2.1
component  : programming.python
summary    : Represents the core of the Zope Component Architecture
description: |
    Represents the core of the Zope Component Architecture.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-zope.event
    - python-zope.hookable
    - python-zope.interface
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
