name       : python-zope.component
version    : 4.3.0
release    : 1
source     :
    - https://github.com/zopefoundation/zope.component/archive/4.3.0.tar.gz : 4db908df2373344c6ef4354ea740faf8441ed2a39b753f5fbb36ab4f363b84d1
license    : ZPL-2.1
component  : programming.python
summary    : Represents the core of the Zope Component Architecture
description: |
    Represents the core of the Zope Component Architecture
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
    - python-zope.event
    - python-zope.interface
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install