name       : python-zope.component
version    : 5.0.1
release    : 9
source     :
    - https://github.com/zopefoundation/zope.component/archive/refs/tags/5.0.1.tar.gz : 984105a38bd04fad28a279a8ee0d6f05cee6264f8f008d91d19fcc84fdc07504
license    : ZPL-2.1
component  : programming.python
summary    : Represents the core of the Zope Component Architecture
description: |
    Represents the core of the Zope Component Architecture.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-zope.deferredimport
    - python-zope.deprecation
    - python-zope.event
    - python-zope.hookable
build      : |
    %python3_setup
install    : |
    %python3_install
