name       : python-zope.component
version    : 4.4.1
release    : 3
source     :
    - https://github.com/zopefoundation/zope.component/archive/4.4.1.tar.gz : 54f57057437fafeeaf7ae9bfe2a2b1743392c4f7f898fc4896cb0a73d67aa0ea
license    : ZPL-2.1
component  : programming.python
summary    : Represents the core of the Zope Component Architecture
description: |
    Represents the core of the Zope Component Architecture
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-zope.event
    - python-zope.interface
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
